### ISSUE TITLE
Pywasm 1.0.4 does not install

### ISSUE THREAD

**Issue by prescod** [mohanson/pywasm#37]
```
 $  pip install pywasm==1.0.0
Collecting pywasm==1.0.0
  Downloading pywasm-1.0.0-py3-none-any.whl (27 kB)
Collecting numpy
  Using cached numpy-1.19.4-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
Installing collected packages: numpy, pywasm
Successfully installed numpy-1.19.4 pywasm-1.0.0

 $  pip install pywasm==1.0.4
Collecting pywasm==1.0.4
  Using cached pywasm-1.0.4.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/pprescod/code/open_source/wasm_api/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0y/kdzktrn95clfn6_8cjfyqvx80000gp/T/pip-install-byir0hq3/pywasm/setup.py'"'"'; __file__='"'"'/private/var/folders/0y/kdzktrn95clfn6_8cjfyqvx80000gp/T/pip-install-byir0hq3/pywasm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0y/kdzktrn95clfn6_8cjfyqvx80000gp/T/pip-pip-egg-info-zfgq73nm
         cwd: /private/var/folders/0y/kdzktrn95clfn6_8cjfyqvx80000gp/T/pip-install-byir0hq3/pywasm/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0y/kdzktrn95clfn6_8cjfyqvx80000gp/T/pip-install-byir0hq3/pywasm/setup.py", line 7, in <module>
        with open(os.path.join(root, 'requirements.txt')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/0y/kdzktrn95clfn6_8cjfyqvx80000gp/T/pip-install-byir0hq3/pywasm/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 20.3.3 is available.
You should consider upgrading via the '/Users/pprescod/code/open_source/wasm_api/.venv/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by mohanson** [comment]
Thanks for your report.  There was a problem with my release script, which has been fixed now. Please reinstall `pywasm==1.0.5`

**Comment by prescod** [comment]
Thank you!
